from django.urls import path, re_path
from . import views


urlpatterns = [
    path('', views.index),
    path('home', views.home),
    path('register', views.register),
    path('register/form', views.register_form),
    path('login', views.login),
    path('logout/', views.logout),
    path('users', views.users),
    path('users/<id>', views.user_profile),
    path('users/<id>/edit', views.user_edit),
    path('edituserinfo', views.edit_user_info),
    path('changepassword', views.change_password),
    path('makeadmin', views.make_admin),
    path('adduser', views.add_user),
    path('adduserpost', views.add_user_post),
    path('search', views.search),
    path('search/process', views.search_process),
    path('search/results', views.search_results),
    path('company/<id>', views.company_info),
    path('company/<id>/edit', views.edit_company_info),
    path('company/<id>/addcontact', views.add_contact),
    path('company/<id>/watchlist', views.process_watchlist),
    path('notfound', views.not_found),
    path('processeditcompany', views.process_edit_company),
    path('processaddcontact', views.process_add_contact),
    path('search/history', views.search_history),
    path('search/<id>', views.view_search),
    path('admin/wall', views.admin_wall),
    path('processcomment', views.process_comment),
    path('processnote', views.process_note),
    path('watchlist', views.watchlist),
    path('processeditcontact', views.process_edit_contact),
    path('editcontact/<id>', views.edit_contact),
    path('deletecontact/<id>', views.delete_contact),
    path('about', views.about),
    re_path(r'^(?P<path>.*)/$', views.bad_request)
]
