# Generated by Django 3.1.4 on 2021-01-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_company_job_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='desc_long',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='desc_short',
            field=models.CharField(default='', max_length=255),
        ),
    ]
