# Generated by Django 3.1.4 on 2021-01-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_auto_20210124_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='searches',
            field=models.ManyToManyField(related_name='companies', to='login_app.Search'),
        ),
    ]
