# Generated by Django 3.1.4 on 2021-01-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0006_company_searches'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date_posted',
            field=models.CharField(default='30+ days ago', max_length=255),
        ),
    ]
