# Generated by Django 3.1.4 on 2021-01-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0007_job_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
