# Generated by Django 3.1.4 on 2021-01-25 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0008_auto_20210124_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indeed', models.CharField(default='/', max_length=255)),
                ('dnb', models.CharField(default='/', max_length=255)),
                ('glassdoor', models.CharField(default='/', max_length=255)),
                ('google', models.CharField(default='/', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='login_app.company')),
            ],
        ),
    ]
