# Generated by Django 3.1.4 on 2021-01-25 16:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0011_company_last_edited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='last_edited_on',
            field=models.DateField(default=datetime.datetime(2021, 1, 25, 16, 19, 25, 996193, tzinfo=utc)),
        ),
    ]
