# Generated by Django 3.1.4 on 2021-01-25 19:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0012_company_last_edited_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='last_edited_on',
            field=models.DateField(default=datetime.datetime(2021, 1, 25, 19, 6, 53, 96342, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('linked_in', models.CharField(default='', max_length=255)),
                ('department', models.CharField(default='', max_length=255)),
                ('position', models.CharField(default='', max_length=255)),
                ('notes', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='login_app.company')),
            ],
        ),
    ]
