# Generated by Django 3.1.4 on 2021-01-25 23:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0013_auto_20210125_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='last_edited_on',
            field=models.DateField(default=datetime.datetime(2021, 1, 25, 23, 5, 0, 395627, tzinfo=utc)),
        ),
    ]
