# Generated by Django 3.1.4 on 2021-01-26 19:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0016_auto_20210126_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='users_who_watchlisted',
            field=models.ManyToManyField(related_name='watchlisted_companies', to='login_app.User'),
        ),
        migrations.AlterField(
            model_name='company',
            name='last_edited_on',
            field=models.DateField(default=datetime.datetime(2021, 1, 26, 19, 0, 35, 837487, tzinfo=utc)),
        ),
    ]
