# Generated by Django 3.1.4 on 2021-01-26 19:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0017_auto_20210126_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='last_edited_on',
            field=models.DateField(default=datetime.datetime(2021, 1, 26, 19, 42, 58, 500877, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='department',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='linked_in',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='notes',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='position',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
