# Generated by Django 3.1.4 on 2021-01-27 15:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0018_auto_20210126_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_login',
            field=models.BooleanField(default='True'),
        ),
        migrations.AlterField(
            model_name='company',
            name='last_edited_on',
            field=models.DateField(default=datetime.datetime(2021, 1, 27, 15, 57, 39, 738877, tzinfo=utc)),
        ),
    ]
